export default {
  category: [
    {
      id: '1',
      categoryName: 'donuts',
      categoryImage: require('./DzPhotos/donuts.png'),
    },
    {
      id: '2',
      categoryName: 'brownies',
      categoryImage: require('./DzPhotos/brownies.png'),
    },
    {
      id: '3',
      categoryName: 'cupcakes',
      categoryImage: require('./DzPhotos/cupcakes.png'),
    },
    {
      id: '4',
      categoryName: 'Macarons',
      categoryImage: require('./DzPhotos/macarons.png'),
    },
    {
      id: '5',
      categoryName: 'Coffee',
      categoryImage: require('./DzPhotos/coffee.png'),
    },
    {
      id: '6',
      categoryName: 'shakes',
      categoryImage: require('./DzPhotos/shakes.png'),
    },
  ],
  product: [
    {
      id: '1',
      categoryId: '1',
      productName: 'salted caramel donut',
      images: require('./DzPhotos/donut1.png'),
      Description:
        'A decadent sweet and salty caramel ganache striped with white chocolate.A classic delight for all ages. Sweet vanilla icing draped over it , topped with a golden caramel drizzle.',
      added: 0,
      price: '2',
      rating: '4.9',
    },
    {
      id: '2',
      categoryId: '1',
      productName: 'cookies and cream donut',
      images: require('./DzPhotos/donut2.png'),
      Description:
        'That’s just the way the cookie crumbles! Indulge your sweet tooth with vanilla icing, Oreo crumbles, and hot fudge drizzle.',
      added: 0,
      price: '2',
      rating: '5',
    },
    {
      id: '3',
      categoryId: '1',
      productName: 'blueberry icing donut',
      images: require('./DzPhotos/donut3.png'),
      Description:
        'Know how to chase away the blues? Coat a made-to-order donut in creamy blueberry icing, then shower it with powdered sugar. Instant happiness!',
      added: 0,
      price: '2',
      rating: '4.5',
    },
    {
      id: '4',
      categoryId: '1',
      productName: 'Double Chocolate',
      images: require('./DzPhotos/donut4.png'),
      Description:
        'These chocolate donuts are baked using only high-quality ingredients so you can enjoy the best tasting donuts.',
      added: 0,
      price: '2',
      rating: '5',
    },
    {
      id: '5',
      categoryId: '1',
      productName: 'Choco-Sprinkle Donut',
      images: require('./DzPhotos/donut5.png'),
      Description:
        'Soft donut covered with decadent chocolate glaze and sprinkles.The glaze is super simple and oh so chocolate-y. And what’s a donut without sprinkles?',
      added: 0,
      price: '2',
      rating: '4.5',
    },
    {
      id: '6',
      categoryId: '1',
      productName: 'Chocolate Chip Coffee Cake Donuts',
      images: require('./DzPhotos/donut6.png'),
      Description:
        'Baked Chocolate Chip Coffee Cake Donuts with a butter crumb topping and full of chocolate chips. Perfect for a weekend breakfast treat!',
      added: 0,
      price: '2',
      rating: '5',
    },
    {
      id: '7',
      categoryId: '1',
      productName: 'Chocolate-Filled Donut',
      images: require('./DzPhotos/donut7.png'),
      Description:
        'With a crispy chocolate base, brigadeiro cream filling and sprinkles, this rich dessert is ridiculously chocolatey.',
      added: 0,
      price: '2',
      rating: '4.6',
    },
    {
      id: '8',
      categoryId: '1',
      productName: 'cheesecake donut',
      images: require('./DzPhotos/donut8.png'),
      Description:
        'Meet the Ring-Filled New York Cheesecake donut,will surely satisfy your sweet tooth,New York Cheesecake filling, frosted with cream cheese icing, topped with graham cracker crumbs.',
      added: 0,
      price: '2',
      rating: '5',
    },
    {
      id: '9',
      categoryId: '1',
      productName: 'chocolate cake donut',
      images: require('./DzPhotos/donut9.png'),
      Description:
        'Chocolate Cake Donuts with a Vanilla Glaze-rich chocolate flavor and dense texture, these are the perfect donuts to make a day ahead.',
      added: 0,
      price: '2',
      rating: '4.4',
    },
    {
      id: '10',
      categoryId: '1',
      productName: 'Strawberry Donut',
      images: require('./DzPhotos/donut10.png'),
      Description:
        'Oven baked and brimming with bright, sweet strawberry flavor – thanks to the use of both fresh strawberries and freeze dried strawberries! They’re soft and tender and finished with the most tempting glaze. Who could resist?',
      added: 0,
      price: '2',
      rating: '4.7',
    },
    {
      id: '11',
      categoryId: '2',
      productName: 'Nutty Brownies',
      images: require('./DzPhotos/brownies11.png'),
      Description:
        'The all-time favorite Nutty Brownies are one of the best-tested ways to woo the friends. Enjoy some fun time with your friends and family over these delicious Nutty Brownies',
      added: 0,
      price: '2',
      rating: '4.4',
    },
    {
      id: '12',
      categoryId: '2',
      productName: 'Cinnamon Cocoa Brownies',
      images: require('./DzPhotos/brownies12.png'),
      Description:
        'Mixed with cinnamon and topped with buttery cocoa pecan crumble. Contains nuts.',
      added: 0,
      price: '2',
      rating: '4.6',
    },
    {
      id: '13',
      categoryId: '2',
      productName: 'Chocolate Chip Brownies',
      images: require('./DzPhotos/brownies13.png'),
      Description:
        'Soft vanilla and brown sugar blondie with Belgian chocolate chips.',
      added: 0,
      price: '2',
      rating: '4.8',
    },
    {
      id: '14',
      categoryId: '2',
      productName: 'Death by Chocolate Brownies',
      images: require('./DzPhotos/brownies14.png'),
      Description:
        'The all-time favorite Death by Chocolate Brownies are one of the best-tested ways to woo the friends. Enjoy some fun time with your friends and family over these delicious Death by Chocolate Brownies',
      added: 0,
      price: '2',
      rating: '4.9',
    },
    {
      id: '15',
      categoryId: '2',
      productName: 'Raspberry White Chocolate brownies',
      images: require('./DzPhotos/brownies15.png'),
      Description:
        'Blondie swirled with raspberry puree and sprinkled with white chocolate chips.',
      added: 0,
      price: '2',
      rating: '4.7',
    },
    {
      id: '16',
      categoryId: '2',
      productName: 'Fudgy Triple Chocolate',
      images: require('./DzPhotos/brownies16.png'),
      Description:
        'These fudgy brownies are made with 3 types of chocolate to give them a rich and decadent chocolate flavor. They’re thick, dense, not the least bit cakey, and taste delicious served plain or with a scoop of vanilla ice cream.',
      added: 0,
      price: '2',
      rating: '4.1',
    },
    {
      id: '17',
      categoryId: '2',
      productName: 'Nutella Brownies',
      images: require('./DzPhotos/brownies17.png'),
      Description:
        'These rich, deeply chocolatey Nutella Brownies are a home run dessert for anybody who loves the indulgent chocolate hazelnut spread. Not only is the brownie batter made with Nutella, but then more is dropped on top .',
      added: 0,
      price: '2',
      rating: '5',
    },
    {
      id: '18',
      categoryId: '3',
      productName: 'vanilla cupcake',
      images: require('./DzPhotos/cupcake18.png'),
      Description:
        'A truly perfect Vanilla Cupcake recipe! These Vanilla Cupcakes are moist,soft and yummy.',
      added: 0,
      price: '2.5',
      rating: '5',
    },
    {
      id: '19',
      categoryId: '3',
      productName: 'Rainbow Cupcakes',
      images: require('./DzPhotos/cupcake19.png'),
      Description:
        'Rainbow base, Vanilla buttercream, Decorated with sprinkles.',
      added: 0,
      price: '2.5',
      rating: '4',
    },
    {
      id: '20',
      categoryId: '3',
      productName: 'Banana and Walnut cupcake',
      images: require('./DzPhotos/cupcake20.png'),
      Description:
        "Relax in your cabana, While you taste a little banana. With a walnut base too, Made fresh just for you. I'm cute & enticing, Finished with cream cheese icing.",
      added: 0,
      price: '2.5',
      rating: '4.3',
    },
    {
      id: '21',
      categoryId: '3',
      productName: 'Chocolate Cupcake',
      images: require('./DzPhotos/cupcake21.png'),
      Description:
        'Chocolate cupcakes, topped off with silky chocolate cream cheese frosting! Rich and dreamy cupcake, perfect for anychocolate fan.',
      added: 0,
      price: '2.5',
      rating: '4.3',
    },
    {
      id: '22',
      categoryId: '3',
      productName: 'Coffee cupcake',
      images: require('./DzPhotos/cupcake22.png'),
      Description:
        'These moist and flavorful chocolate cupcakes paired with creamy coffee frosting make the perfect rich and decadent dessert!',
      added: 0,
      price: '2.5',
      rating: '4',
    },
    {
      id: '23',
      categoryId: '4',
      productName: 'Bubblegum macaron',
      images: require('./DzPhotos/macaron23.png'),
      Description:
        'Bubblegum flavoured buttercream filling,this delicious experience will be completely fulfilling!',
      added: 0,
      price: '2.5',
      rating: '4.2',
    },
    {
      id: '24',
      categoryId: '4',
      productName: 'cookies and cream macaron',
      images: require('./DzPhotos/macaron24.png'),
      Description:
        'Hey there dessert lover , Well if you don’t try this your insane.Because cookies and cream is the best combination.',
      added: 0,
      price: '2.5',
      rating: '4',
    },
    {
      id: '25',
      categoryId: '4',
      productName: 'Blue nutella macaron',
      images: require('./DzPhotos/macaron25.png'),
      Description:
        'The macaron filled with Nutella and biscuit shell has the colour of a blue sky,this is so yummy, you need this.',
      added: 0,
      price: '2.5',
      rating: '4.2',
    },
    {
      id: '26',
      categoryId: '4',
      productName: 'Peanut butter macaron',
      images: require('./DzPhotos/macaron26.jpg'),
      Description:
        'Savoury and sweet,filled with peanut butter flavoured buttercream.',
      added: 0,
      price: '2.5',
      rating: '4.1',
    },
    {
      id: '27',
      categoryId: '4',
      productName: 'Strawberry and cream macaron',
      images: require('./DzPhotos/macaron27.jpg'),
      Description:
        "Perfect at any party no matter the theme,because who doesn't like strawberry & cream?Perfect macaron for you and your friends will love.",
      added: 0,
      price: '2.5',
      rating: '4',
    },
    {
      id: '28',
      categoryId: '5',
      productName: 'Irish coffee',
      images: require('./DzPhotos/coffee28.png'),
      Description:
        "Irish coffee is one the most classic coffee mixed drinks. It is the perfect combination of sweetened coffee, Irish whiskey, and (of course) whipped cream . It's cozy, delicious.",
      added: 0,
      price: '4',
      rating: '4.6',
    },
    {
      id: '29',
      categoryId: '5',
      productName: 'latte macchiato',
      images: require('./DzPhotos/coffee29.png'),
      Description:
        'The hot milk and creamy milk foam are imbued with the delicious flavour of coffee for a spectacular, sumptuous result. This will delight all gourmets!',
      added: 0,
      price: '4',
      rating: '5',
    },
    {
      id: '30',
      categoryId: '5',
      productName: 'Cappuccino',
      images: require('./DzPhotos/coffee30.png'),
      Description:
        'Light, foamy cappuccinos are a favorite drink for many coffee lovers.Equal parts double espresso, steamed milk, and steamed milk foam on top.',
      added: 0,
      price: '4',
      rating: '4.5',
    },
    {
      id: '31',
      categoryId: '5',
      productName: 'Mocha ',
      images: require('./DzPhotos/coffee31.png'),
      Description:
        'Delicious dark chocolate mocha is perfect for chocolate lover , this Hot creamy mocha gives the great taste.',
      added: 0,
      price: '4',
      rating: '4.3',
    },
    {
      id: '32',
      categoryId: '5',
      productName: 'Iced Mocha',
      images: require('./DzPhotos/coffee32.png'),
      Description:
        'Our rich, full-bodied espresso combined with bittersweet mocha sauce, milk and ice, then topped with sweetened whipped cream. ',
      added: 0,
      price: '4',
      rating: '4.8',
    },
    {
      id: '33',
      categoryId: '6',
      productName: 'Chocolate shake',
      images: require('./DzPhotos/shake33.png'),
      Description:
        'This chocolate milkshake with icecream is a delicious drink that you absolutely have to try.',
      added: 0,
      price: '4',
      rating: '4.3',
    },
    {
      id: '34',
      categoryId: '6',
      productName: 'strawberry shake',
      images: require('./DzPhotos/shake34.png'),
      Description:
        'This milkshake is made with strawberry ice cream and fresh strawberries, healthy and yummy!',
      added: 0,
      price: '4',
      rating: '4.7',
    },
    {
      id: '35',
      categoryId: '6',
      productName: 'Vanilla shake',
      images: require('./DzPhotos/shake35.jpg'),
      Description:
        'This icy classic vanilla shake tastes amazing and will keep you cool .With whipped cream, sugar free chocolate syrup.',
      added: 0,
      price: '4',
      rating: '4',
    },
    {
      id: '36',
      categoryId: '6',
      productName: 'blueberry shake',
      images: require('./DzPhotos/shake36.png'),
      Description:
        'This creamy and refreshing blueberry smoothie is made with juice, yogurt, frozen blueberries and banana, all blended together into a frosty drink.',
      added: 0,
      price: '4',
      rating: '5',
    },
  ],
};
